2024-05-07 19:32:00.657421: I tensorflow/core/util/port.cc:113] oneDNN custom operations are on. You may see slightly different numerical results due to floating-point round-off errors from different computation orders. To turn them off, set the environment variable `TF_ENABLE_ONEDNN_OPTS=0`.
2024-05-07 19:32:01.791411: I tensorflow/core/util/port.cc:113] oneDNN custom operations are on. You may see slightly different numerical results due to floating-point round-off errors from different computation orders. To turn them off, set the environment variable `TF_ENABLE_ONEDNN_OPTS=0`.
2024-05-07 19:32:04.312586: I tensorflow/core/platform/cpu_feature_guard.cc:210] This TensorFlow binary is optimized to use available CPU instructions in performance-critical operations.
To enable the following instructions: AVX2 FMA, in other operations, rebuild TensorFlow with the appropriate compiler flags.
WARNING:absl:Compiled the loaded model, but the compiled metrics have yet to be built. `model.compile_metrics` will be empty until you train or evaluate the model.
WARNING:tensorflow:From C:\Users\skm99\AppData\Local\Programs\Python\Python312\Lib\site-packages\keras\src\backend\tensorflow\core.py:184: The name tf.placeholder is deprecated. Please use tf.compat.v1.placeholder instead.

WARNING:tensorflow:From C:\Users\skm99\AppData\Local\Programs\Python\Python312\Lib\site-packages\keras\src\backend\tensorflow\core.py:184: The name tf.placeholder is deprecated. Please use tf.compat.v1.placeholder instead.

Traceback (most recent call last):
  File "C:\Users\skm99\OneDrive\Desktop\¼ö¾÷ÀÚ·á\spring boot\testSpring\src\main\java\com\board\pet.py", line 53, in <module>
    predicted_breed = predict_breed(image_path)
                      ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\skm99\OneDrive\Desktop\¼ö¾÷ÀÚ·á\spring boot\testSpring\src\main\java\com\board\pet.py", line 47, in predict_breed
    prediction = model.predict(features)
                 ^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\skm99\AppData\Local\Programs\Python\Python312\Lib\site-packages\keras\src\utils\traceback_utils.py", line 122, in error_handler
    raise e.with_traceback(filtered_tb) from None
  File "C:\Users\skm99\AppData\Local\Programs\Python\Python312\Lib\site-packages\keras\src\models\functional.py", line 288, in _adjust_input_rank
    raise ValueError(
ValueError: Exception encountered when calling Sequential.call().

[1mInvalid input shape for input Tensor("data:0", shape=(1, 125, 125, 3), dtype=float32). Expected shape (None, 9664), but input has incompatible shape (1, 125, 125, 3)[0m

Arguments received by Sequential.call():
  \u2022 inputs=tf.Tensor(shape=(1, 125, 125, 3), dtype=float32)
  \u2022 training=False
  \u2022 mask=None
